# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     Pulsars_Debug
#     Pulsars_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files\Analog Devices\VisualDSP 5.0


# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "Pulsars_Debug" configuration
#

ifeq ($(MAKECMDGOALS),Pulsars_Debug)

Pulsars_Debug : ./Debug/Pulsars.dxe 

./Debug/Buffers.doj :./Buffers.asm 
	@echo ".\Buffers.asm"
	$(VDSP)/easmblkfn.exe .\Buffers.asm -proc ADSP-BF537 -file-attr ProjectName=Pulsars -g -si-revision 0.3 -o .\Debug\Buffers.doj -MM

./Debug/Observation.doj :./Observation.asm ./uartlib.h $(VDSP)/Blackfin/include/defBF534.h $(VDSP)/Blackfin/include/defBF537.h $(VDSP)/Blackfin/include/def_LPBlackfin.h 
	@echo ".\Observation.asm"
	$(VDSP)/easmblkfn.exe .\Observation.asm -proc ADSP-BF537 -file-attr ProjectName=Pulsars -g -si-revision 0.3 -o .\Debug\Observation.doj -MM

./Debug/Pulsars.doj :./Pulsars.asm 
	@echo ".\Pulsars.asm"
	$(VDSP)/easmblkfn.exe .\Pulsars.asm -proc ADSP-BF537 -file-attr ProjectName=Pulsars -g -si-revision 0.3 -o .\Debug\Pulsars.doj -MM

./Debug/Pulsars_basiccrt.doj :./Pulsars_basiccrt.s $(VDSP)/Blackfin/include/defBF534.h $(VDSP)/Blackfin/include/defBF537.h $(VDSP)/Blackfin/include/def_LPBlackfin.h $(VDSP)/Blackfin/include/sys/_adi_platform.h $(VDSP)/Blackfin/include/sys/anomaly_macros_rtl.h $(VDSP)/Blackfin/include/sys/platform.h 
	@echo ".\Pulsars_basiccrt.s"
	$(VDSP)/easmblkfn.exe .\Pulsars_basiccrt.s -proc ADSP-BF537 -file-attr ProjectName=Pulsars -g -si-revision 0.3 -o .\Debug\Pulsars_basiccrt.doj -MM

Debug/Pulsars_heaptab.doj :Pulsars_heaptab.c 
	@echo ".\Pulsars_heaptab.c"
	$(VDSP)/ccblkfn.exe -c .\Pulsars_heaptab.c -file-attr ProjectName=Pulsars -g -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -si-revision 0.3 -proc ADSP-BF537 -o .\Debug\Pulsars_heaptab.doj -MM

./Debug/Supervisor.doj :./Supervisor.asm ./uartlib.h $(VDSP)/Blackfin/include/defBF534.h $(VDSP)/Blackfin/include/defBF537.h $(VDSP)/Blackfin/include/def_LPBlackfin.h 
	@echo ".\Supervisor.asm"
	$(VDSP)/easmblkfn.exe .\Supervisor.asm -proc ADSP-BF537 -file-attr ProjectName=Pulsars -g -si-revision 0.3 -o .\Debug\Supervisor.doj -MM

./Debug/uartlib.doj :./uartlib.asm $(VDSP)/Blackfin/include/defBF534.h $(VDSP)/Blackfin/include/defBF537.h $(VDSP)/Blackfin/include/def_LPBlackfin.h 
	@echo ".\uartlib.asm"
	$(VDSP)/easmblkfn.exe .\uartlib.asm -proc ADSP-BF537 -file-attr ProjectName=Pulsars -g -si-revision 0.3 -o .\Debug\uartlib.doj -MM

./Debug/Pulsars.dxe :./Pulsars.ldf ./Debug/Pulsars_basiccrt.doj $(VDSP)/Blackfin/lib/bf534_rev_0.3/libprofile532y.dlb ./Debug/Buffers.doj ./Debug/Observation.doj ./Debug/Pulsars.doj ./Debug/Pulsars_heaptab.doj ./Debug/Supervisor.doj ./Debug/uartlib.doj $(VDSP)/Blackfin/lib/cplbtab537.doj $(VDSP)/Blackfin/lib/bf534_rev_0.3/crtn532y.doj $(VDSP)/Blackfin/lib/bf534_rev_0.3/libsmall532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libio532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libc532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libevent532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libx532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libcpp532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libcpprt532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libf64ieee532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libdsp532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libsftflt532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/libetsi532y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/Debug/libssl537y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/Debug/libdrv537y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/Debug/libusb537y.dlb $(VDSP)/Blackfin/lib/bf534_rev_0.3/idle532mty.doj $(VDSP)/Blackfin/lib/bf534_rev_0.3/librt_fileio532y.dlb 
	@echo "Linking..."
	$(VDSP)/ccblkfn.exe .\Debug\Buffers.doj .\Debug\Observation.doj .\Debug\Pulsars.doj .\Debug\Pulsars_basiccrt.doj .\Debug\Pulsars_heaptab.doj .\Debug\Supervisor.doj .\Debug\uartlib.doj -T .\Pulsars.ldf -L .\Debug -flags-link -MDUSER_CRT=ADI_QUOTEPulsars_basiccrt.dojADI_QUOTE,-MDUSE_FILEIO,-MD__cplusplus -add-debug-libpaths -flags-link -od,.\Debug -o .\Debug\Pulsars.dxe -proc ADSP-BF537 -si-revision 0.3 -flags-link -MM

endif

ifeq ($(MAKECMDGOALS),Pulsars_Debug_clean)

Pulsars_Debug_clean:
	-$(RM) ".\Debug\Buffers.doj"
	-$(RM) ".\Debug\Observation.doj"
	-$(RM) ".\Debug\Pulsars.doj"
	-$(RM) ".\Debug\Pulsars_basiccrt.doj"
	-$(RM) "Debug\Pulsars_heaptab.doj"
	-$(RM) ".\Debug\Supervisor.doj"
	-$(RM) ".\Debug\uartlib.doj"
	-$(RM) ".\Debug\Pulsars.dxe"
	-$(RM) ".\Debug\*.ipa"
	-$(RM) ".\Debug\*.opa"
	-$(RM) ".\Debug\*.ti"
	-$(RM) ".\Debug\*.pgi"
	-$(RM) ".\*.rbld"

endif


